"""Generated by cppwg genpackage - do not edit.

Compiled-extension imports and TemplateClass subscript stubs for this
subpackage. Hand-written code (TemplateMethod attachments, package init,
curation) belongs in the sibling __init__.py, which does `from ._generated
import *`.
"""

from chaste._pychaste_all import (
    CellPopulationPyChasteActorGenerator_2,
    CellPopulationPyChasteActorGenerator_3,
    VtkScene_2,
    VtkScene_3,
)
from chaste._syntax import TemplateClass

__all__ = [
    "CellPopulationPyChasteActorGenerator",
    "CellPopulationPyChasteActorGenerator_2",
    "CellPopulationPyChasteActorGenerator_3",
    "VtkScene",
    "VtkScene_2",
    "VtkScene_3",
]


class CellPopulationPyChasteActorGenerator(TemplateClass):
    _instantiations = {
        ("2",): CellPopulationPyChasteActorGenerator_2,
        ("3",): CellPopulationPyChasteActorGenerator_3,
    }


class VtkScene(TemplateClass):
    _instantiations = {
        ("2",): VtkScene_2,
        ("3",): VtkScene_3,
    }
