"""Generated by cppwg genpackage - do not edit.

Compiled-extension imports and TemplateClass subscript stubs for this
subpackage. Hand-written code (TemplateMethod attachments, package init,
curation) belongs in the sibling __init__.py, which does `from ._generated
import *`.
"""

__copyright__ = """Copyright (c) 2005-2026, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from chaste._pychaste_all import (
    AveragedSourceEllipticPde_1,
    AveragedSourceEllipticPde_2,
    AveragedSourceEllipticPde_3,
    AveragedSourceParabolicPde_1,
    AveragedSourceParabolicPde_2,
    AveragedSourceParabolicPde_3,
    CellBasedEllipticPdeSolver_1,
    CellBasedEllipticPdeSolver_2,
    CellBasedEllipticPdeSolver_3,
    CellBasedParabolicPdeSolver_1,
    CellBasedParabolicPdeSolver_2,
    CellBasedParabolicPdeSolver_3,
    CellwiseSourceEllipticPde_1,
    CellwiseSourceEllipticPde_2,
    CellwiseSourceEllipticPde_3,
    CellwiseSourceParabolicPde_1,
    CellwiseSourceParabolicPde_2,
    CellwiseSourceParabolicPde_3,
    ConstBoundaryCondition_1,
    ConstBoundaryCondition_2,
    ConstBoundaryCondition_3,
    EllipticBoxDomainPdeModifier_1,
    EllipticBoxDomainPdeModifier_2,
    EllipticBoxDomainPdeModifier_3,
    EllipticGrowingDomainPdeModifier_1,
    EllipticGrowingDomainPdeModifier_2,
    EllipticGrowingDomainPdeModifier_3,
    ParabolicBoxDomainPdeModifier_1,
    ParabolicBoxDomainPdeModifier_2,
    ParabolicBoxDomainPdeModifier_3,
    ParabolicGrowingDomainPdeModifier_1,
    ParabolicGrowingDomainPdeModifier_2,
    ParabolicGrowingDomainPdeModifier_3,
    PdeSimulationTime,
    UniformSourceEllipticPde_1,
    UniformSourceEllipticPde_2,
    UniformSourceEllipticPde_3,
    UniformSourceParabolicPde_1,
    UniformSourceParabolicPde_2,
    UniformSourceParabolicPde_3,
)
from chaste._syntax import TemplateClass

__all__ = [
    "AveragedSourceEllipticPde",
    "AveragedSourceEllipticPde_1",
    "AveragedSourceEllipticPde_2",
    "AveragedSourceEllipticPde_3",
    "AveragedSourceParabolicPde",
    "AveragedSourceParabolicPde_1",
    "AveragedSourceParabolicPde_2",
    "AveragedSourceParabolicPde_3",
    "CellBasedEllipticPdeSolver",
    "CellBasedEllipticPdeSolver_1",
    "CellBasedEllipticPdeSolver_2",
    "CellBasedEllipticPdeSolver_3",
    "CellBasedParabolicPdeSolver",
    "CellBasedParabolicPdeSolver_1",
    "CellBasedParabolicPdeSolver_2",
    "CellBasedParabolicPdeSolver_3",
    "CellwiseSourceEllipticPde",
    "CellwiseSourceEllipticPde_1",
    "CellwiseSourceEllipticPde_2",
    "CellwiseSourceEllipticPde_3",
    "CellwiseSourceParabolicPde",
    "CellwiseSourceParabolicPde_1",
    "CellwiseSourceParabolicPde_2",
    "CellwiseSourceParabolicPde_3",
    "ConstBoundaryCondition",
    "ConstBoundaryCondition_1",
    "ConstBoundaryCondition_2",
    "ConstBoundaryCondition_3",
    "EllipticBoxDomainPdeModifier",
    "EllipticBoxDomainPdeModifier_1",
    "EllipticBoxDomainPdeModifier_2",
    "EllipticBoxDomainPdeModifier_3",
    "EllipticGrowingDomainPdeModifier",
    "EllipticGrowingDomainPdeModifier_1",
    "EllipticGrowingDomainPdeModifier_2",
    "EllipticGrowingDomainPdeModifier_3",
    "ParabolicBoxDomainPdeModifier",
    "ParabolicBoxDomainPdeModifier_1",
    "ParabolicBoxDomainPdeModifier_2",
    "ParabolicBoxDomainPdeModifier_3",
    "ParabolicGrowingDomainPdeModifier",
    "ParabolicGrowingDomainPdeModifier_1",
    "ParabolicGrowingDomainPdeModifier_2",
    "ParabolicGrowingDomainPdeModifier_3",
    "PdeSimulationTime",
    "UniformSourceEllipticPde",
    "UniformSourceEllipticPde_1",
    "UniformSourceEllipticPde_2",
    "UniformSourceEllipticPde_3",
    "UniformSourceParabolicPde",
    "UniformSourceParabolicPde_1",
    "UniformSourceParabolicPde_2",
    "UniformSourceParabolicPde_3",
]


class AveragedSourceEllipticPde(TemplateClass):
    _instantiations = {
        ("1",): AveragedSourceEllipticPde_1,
        ("2",): AveragedSourceEllipticPde_2,
        ("3",): AveragedSourceEllipticPde_3,
    }


class AveragedSourceParabolicPde(TemplateClass):
    _instantiations = {
        ("1",): AveragedSourceParabolicPde_1,
        ("2",): AveragedSourceParabolicPde_2,
        ("3",): AveragedSourceParabolicPde_3,
    }


class CellBasedEllipticPdeSolver(TemplateClass):
    _instantiations = {
        ("1",): CellBasedEllipticPdeSolver_1,
        ("2",): CellBasedEllipticPdeSolver_2,
        ("3",): CellBasedEllipticPdeSolver_3,
    }


class CellBasedParabolicPdeSolver(TemplateClass):
    _instantiations = {
        ("1",): CellBasedParabolicPdeSolver_1,
        ("2",): CellBasedParabolicPdeSolver_2,
        ("3",): CellBasedParabolicPdeSolver_3,
    }


class CellwiseSourceEllipticPde(TemplateClass):
    _instantiations = {
        ("1",): CellwiseSourceEllipticPde_1,
        ("2",): CellwiseSourceEllipticPde_2,
        ("3",): CellwiseSourceEllipticPde_3,
    }


class CellwiseSourceParabolicPde(TemplateClass):
    _instantiations = {
        ("1",): CellwiseSourceParabolicPde_1,
        ("2",): CellwiseSourceParabolicPde_2,
        ("3",): CellwiseSourceParabolicPde_3,
    }


class ConstBoundaryCondition(TemplateClass):
    _instantiations = {
        ("1",): ConstBoundaryCondition_1,
        ("2",): ConstBoundaryCondition_2,
        ("3",): ConstBoundaryCondition_3,
    }


class EllipticBoxDomainPdeModifier(TemplateClass):
    _instantiations = {
        ("1",): EllipticBoxDomainPdeModifier_1,
        ("2",): EllipticBoxDomainPdeModifier_2,
        ("3",): EllipticBoxDomainPdeModifier_3,
    }


class EllipticGrowingDomainPdeModifier(TemplateClass):
    _instantiations = {
        ("1",): EllipticGrowingDomainPdeModifier_1,
        ("2",): EllipticGrowingDomainPdeModifier_2,
        ("3",): EllipticGrowingDomainPdeModifier_3,
    }


class ParabolicBoxDomainPdeModifier(TemplateClass):
    _instantiations = {
        ("1",): ParabolicBoxDomainPdeModifier_1,
        ("2",): ParabolicBoxDomainPdeModifier_2,
        ("3",): ParabolicBoxDomainPdeModifier_3,
    }


class ParabolicGrowingDomainPdeModifier(TemplateClass):
    _instantiations = {
        ("1",): ParabolicGrowingDomainPdeModifier_1,
        ("2",): ParabolicGrowingDomainPdeModifier_2,
        ("3",): ParabolicGrowingDomainPdeModifier_3,
    }


class UniformSourceEllipticPde(TemplateClass):
    _instantiations = {
        ("1",): UniformSourceEllipticPde_1,
        ("2",): UniformSourceEllipticPde_2,
        ("3",): UniformSourceEllipticPde_3,
    }


class UniformSourceParabolicPde(TemplateClass):
    _instantiations = {
        ("1",): UniformSourceParabolicPde_1,
        ("2",): UniformSourceParabolicPde_2,
        ("3",): UniformSourceParabolicPde_3,
    }
