#!/bin/sh

# Shell script to create an MPEG format movie using MPlayer from the 
# image0*.png files in the anim folder

# Various parameters
INPUT_FILES="mf://image0*png"
MF_OPTIONS="fps=25:type=png"
VIDEO_CODEC="lavc"
AUDIO_CODEC="copy"
OUTPUT_FILE="simulation.mpeg"
OPT="vbitrate=2160000:mbd=2:keyint=132:vqblur=1.0:cmp=2:subcmp=2:dia=2:mv0:last_pred=3"
LAVC_OPTIONS="vcodec=msmpeg4v2:mbd=2:trell:"$OPT
FRAMESPERSEC="25.0" #Default
#FRAMESPERSEC="2.5" #Slow down movie

echo "You must have mplayer/mencoder installed to use this (yum install mplayer)"

# Encode movie
mencoder $INPUT_FILES -mf $MF_OPTIONS -ovc $VIDEO_CODEC -lavcopts $LAVC_OPTIONS -oac $AUDIO_CODEC -fps $FRAMESPERSEC -o $OUTPUT_FILE

# Play movie on a loop
mplayer -vo x11 -loop 0 simulation.mpeg
