version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
