name: pychaste-tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

# Limit concurrent runs to one per branch
concurrency:
  group: pychaste-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pychaste-tests:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:off') }}

    runs-on: ubuntu-22.04
    env:
      CHASTE_TEST_OUTPUT: ${{ github.workspace }}/chaste_test_output

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make build and test directories
        run: |
          mkdir -p build
          mkdir -p ${CHASTE_TEST_OUTPUT}

      - name: Install Chaste dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake \
            cmake-curses-gui \
            doxygen \
            g++ \
            git \
            gnuplot \
            graphviz \
            hdf5-tools \
            lcov \
            libboost-serialization-dev \
            libboost-filesystem-dev \
            libboost-program-options-dev \
            libfltk1.1 \
            libhdf5-openmpi-dev \
            libmetis-dev \
            libopenmpi-dev \
            libparmetis-dev \
            libpetsc-real3.15-dbg \
            libsundials-dev \
            libvtk7-dev \
            libxerces-c-dev \
            mencoder \
            paraview \
            petsc-dev \
            python3 \
            python3-dev \
            python3-pip \
            python3-venv \
            valgrind \
            xsdcxx

      - name: Install PyChaste-specific dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            castxml \
            python3-matplotlib \
            python3-notebook \
            python3-numpy \
            python3-petsc4py \
            python3-pytest \
            python3-six \
            python3-vtk7 \
            python3-xvfbwrapper \
            xvfb
          sudo python3 -m pip install --upgrade pip
          sudo pip install pygccxml pyyaml

      - name: Configure
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Generate wrappers for comparison
        run: |
          cd build
          make generate_pychaste_wrappers_diff

      - name: Compare wrappers
        run: |
          python -m unittest pychaste/test/python/TestWrapperDiff.py

      - name: Build
        run: |
          cd build
          make -j $(nproc) chaste_pychaste_modules

      - name: Install
        run: |
          cd build/pychaste/python
          pip install --user .

      - name: Run tests
        run: |
          cd build
          xvfb-run --server-args="-screen 0 1024x768x24" \
            ctest -j $(nproc) -L PyChaste --output-on-failure
