option(ENABLE_GLOBAL_TESTING "Generate the test infrastructure for the global component" ON)
mark_as_advanced(ENABLE_GLOBAL_TESTING)
option(ENABLE_IO_TESTING "Generate the test infrastructure for the io component" ON)
mark_as_advanced(ENABLE_IO_TESTING)
option(ENABLE_LINALG_TESTING "Generate the test infrastructure for the linalg component" ON)
mark_as_advanced(ENABLE_LINALG_TESTING)
option(ENABLE_MESH_TESTING "Generate the test infrastructure for the mesh component" ON)
mark_as_advanced(ENABLE_MESH_TESTING)
option(ENABLE_ODE_TESTING "Generate the test infrastructure for the ode component" ON)
mark_as_advanced(ENABLE_ODE_TESTING)
option(ENABLE_PDE_TESTING "Generate the test infrastructure for the pde component" ON)
mark_as_advanced(ENABLE_PDE_TESTING)
option(ENABLE_CELL_BASED_TESTING "Generate the test infrastructure for the cell_based component" ON)
mark_as_advanced(ENABLE_CELL_BASED_TESTING)
option(ENABLE_CRYPT_TESTING "Generate the test infrastructure for the crypt component" ON)
mark_as_advanced(ENABLE_CRYPT_TESTING)
