#!/usr/bin/env bash
# Regenerate the PyChaste C++ wrappers and the Python package.
#
# Parts of the Python package (each subpackage's _generated.py) is generated by
# `cppwg genpackage` from the manually curated package_layout.yaml and the
# automatically generated cppwg_package_model.json.
# Do not hand-edit the _generated.py files.
#
# Usage:
#   regenerate.sh <build-dir> [--package-only]
#   CHASTE_BUILD_DIR=<build-dir> regenerate.sh [--package-only]
#
# <build-dir> is the CMake build directory.
# --package-only regenerates just the _generated.py files.
set -euo pipefail

_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_build_dir="${1:-${CHASTE_BUILD_DIR:-}}"
if [ -z "$_build_dir" ]; then
    echo "usage: regenerate.sh <build-dir> [--package-only]" >&2
    exit 2
fi

# 1. Regenerate the C++ wrappers and cppwg_package_model.json (skip for --package-only).
if [ "${2:-}" != "--package-only" ]; then
    cmake --build "$_build_dir" --target pychaste_wrappers
fi

# 2. Regenerate the Python package layer (_generated.py) from the model.
if [ -x "$_build_dir/chaste_python3_venv/bin/cppwg" ]; then
    # Prefer the cppwg in the build venv
    _cppwg="$_build_dir/chaste_python3_venv/bin/cppwg"
elif command -v cppwg >/dev/null 2>&1; then
    # Fall back to a cppwg on PATH
    _cppwg="cppwg"
else
    echo "error: cppwg not found in $_build_dir/chaste_python3_venv/bin or on PATH;" \
         "build the pychaste target first, or install cppwg" >&2
    exit 1
fi

"$_cppwg" genpackage \
    --model "$_build_dir/pychaste/wrappers/cppwg_package_model.json" \
    --layout "$_script_dir/package_layout.yaml"

# 3. Stamp the generated Python files with the Chaste copyright notice.
#    CheckForCopyrights.py -new inserts the notice below each file's module
#    docstring. Files that already carry it (the hand-written __init__.py etc.)
#    are left unchanged.
_chaste_root="$(cd "$_script_dir/../.." && pwd)"
_package_dir="$(cd "$_chaste_root/pychaste/src/py/chaste" && pwd)"
python3 "$_chaste_root/python/infra/CheckForCopyrights.py" -new -dir "$_package_dir"
