"""Cell-Based Module"""

__copyright__ = """Copyright (c) 2005-2026, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

# The compiled-extension imports and TemplateClass stubs are generated by
# cppwg genpackage into _generated.py (see dynamic/package_layout.yaml);
# add any hand-written code here.
from ._generated import *  # noqa: F401,F403
from chaste._syntax import TemplateMethod
from chaste.cell_based._fortests import (
    AbstractCellBasedTestSuite,
    AbstractCellBasedWithTimingsTestSuite,
    SetupNotebookTest,
    TearDownNotebookTest,
)


# Add TemplateMethods for cell population writer methods to all cell population
# classes so the subscript syntax form works, e.g.
# population.AddCellWriter[CellVolumesWriter]() in place of
# population.AddCellWriter_CellVolumesWriter().
# The plain non-templated method overload which is inherited from
# AbstractCellPopulation is kept as a fallback, so that
# population.AddCellWriter(writer) still works.
#
# The loop below essentially does:
#     PottsBasedCellPopulation_2.AddCellWriter = TemplateMethod(
#         "AddCellWriter",
#         PottsBasedCellPopulation_2.AddCellWriter
#     )
# and likewise for PottsBasedCellPopulation_3, ... , and also for the other
# writer methods, repeated for all the other cell population classes.

# The list of cell population writer methods to add subscript syntax for.
_WRITER_METHOD_BASES = (
    "AddCellWriter",
    "AddCellPopulationCountWriter",
    "AddCellPopulationEventWriter",
    "AddPopulationWriter",
)


def _add_cell_population_writer_subscript_syntax(namespace):
    for obj in list(namespace.values()):
        if not isinstance(obj, type):
            continue
        for base in _WRITER_METHOD_BASES:
            if isinstance(obj.__dict__.get(base), TemplateMethod):
                continue  # already wired
            # Add a relevant TemplateMethod for any class that carries one of
            # the methods in the list such as AddCellWriter_CellVolumesWriter.
            if any(name.startswith(base + "_") for name in dir(obj)):
                setattr(obj, base, TemplateMethod(base, getattr(obj, base, None)))


_add_cell_population_writer_subscript_syntax(globals())
