"""Copyright (c) 2005-2026, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import os
import re
import unittest

import chaste
import chaste.cell_based
import chaste.core
import chaste.mesh
import chaste.ode
import chaste.pde
import chaste.visualization
from chaste import *
from chaste._syntax import TemplateClass
from chaste.cell_based import *
from chaste.core import *
from chaste.mesh import *
from chaste.ode import *
from chaste.pde import *
from chaste.visualization import *

# Parts of the Python package (each subpackage's _generated.py) is generated by
# `cppwg genpackage` from the manually curated package_layout.yaml and the
# automatically generated cppwg_package_model.json. The _generated.py files must
# not be hand-edited. To fix a failure below, list the class under the correct
# subpackage in package_layout.yaml run regenerate.sh.
REGEN_HINT = (
    "\n-- The Python package contains _generated.py files is generated by"
    " `cppwg genpackage` into subpackage; do not hand-edit these."
    "\n-- Assign the class to a subpackage in pychaste/dynamic/package_layout.yaml,"
    " then regenerate by running pychaste/dynamic/regenerate.sh <build-dir>."
)


class TestPyImports(unittest.TestCase):

    def test_imports(self):
        module_wrapper = os.path.abspath("wrappers/all/_pychaste_all.main.cppwg.cpp")
        class_names = []

        class_regex = re.compile(r"^\s*register_(\w+)_class\(m\);\s*$")
        with open(module_wrapper, "r") as f:
            lines = f.readlines()

        for line in lines:
            class_match = class_regex.match(line)
            if class_match:
                class_name = class_match.groups(0)[0]
                # Skip abstract classes, which are not exposed to Python
                if not class_name.startswith("Abstract"):
                    class_names.append(class_name)

        for class_name in class_names:
            # Check that wrapped classes are imported in PyChaste
            clas = globals().get(class_name, None)
            self.assertTrue(
                clas is not None,
                f"\nClass {class_name} is wrapped but not imported in PyChaste"
                + REGEN_HINT,
            )

            # Extra checks for templated classes
            if "_" in class_name:
                template_name, *args = class_name.split("_")
                template = globals().get(template_name, None)

                # Templated classes should have a TemplateClass entry
                defined = (
                    template is not None
                    and isinstance(template, type)
                    and issubclass(template, TemplateClass)
                )
                self.assertTrue(
                    defined,
                    f"\nClass {class_name} does not have a corresponding TemplateClass entry"
                    + REGEN_HINT,
                )

                # Check that the TemplateClass returns the correct type
                self.assertEqual(
                    template[tuple(args)],
                    clas,
                    f"\nTemplatedClass {template_name}[{args}] does not return {class_name}"
                    + REGEN_HINT,
                )


if __name__ == "__main__":
    unittest.main()
