#ifndef ImmersedBoundaryHoneycombMeshGenerator_hpp__cppwg_wrapper
#define ImmersedBoundaryHoneycombMeshGenerator_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundaryHoneycombMeshGenerator_class(pybind11::module &m);
#endif // ImmersedBoundaryHoneycombMeshGenerator_hpp__cppwg_wrapper
