#ifndef VolumeDependentAveragedSourceEllipticPde2_hpp__cppwg_wrapper
#define VolumeDependentAveragedSourceEllipticPde2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_VolumeDependentAveragedSourceEllipticPde2_class(pybind11::module &m);
#endif // VolumeDependentAveragedSourceEllipticPde2_hpp__cppwg_wrapper
