#ifndef AbstractCellPopulationEventWriter3_3_hpp__cppwg_wrapper
#define AbstractCellPopulationEventWriter3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractCellPopulationEventWriter3_3_class(pybind11::module &m);
#endif // AbstractCellPopulationEventWriter3_3_hpp__cppwg_wrapper
