#ifndef AbstractCellPopulationCountWriter2_2_hpp__cppwg_wrapper
#define AbstractCellPopulationCountWriter2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractCellPopulationCountWriter2_2_class(pybind11::module &m);
#endif // AbstractCellPopulationCountWriter2_2_hpp__cppwg_wrapper
