#ifndef AbstractCentreBasedCellPopulation3_3_hpp__cppwg_wrapper
#define AbstractCentreBasedCellPopulation3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractCentreBasedCellPopulation3_3_class(pybind11::module &m);
#endif // AbstractCentreBasedCellPopulation3_3_hpp__cppwg_wrapper
