#ifndef AbstractCellPopulationBoundaryCondition2_2_hpp__cppwg_wrapper
#define AbstractCellPopulationBoundaryCondition2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractCellPopulationBoundaryCondition2_2_class(pybind11::module &m);
#endif // AbstractCellPopulationBoundaryCondition2_2_hpp__cppwg_wrapper
