#ifndef AbstractOffLatticeCellPopulation2_2_hpp__cppwg_wrapper
#define AbstractOffLatticeCellPopulation2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractOffLatticeCellPopulation2_2_class(pybind11::module &m);
#endif // AbstractOffLatticeCellPopulation2_2_hpp__cppwg_wrapper
