#ifndef AbstractCentreBasedCellPopulation2_2_hpp__cppwg_wrapper
#define AbstractCentreBasedCellPopulation2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractCentreBasedCellPopulation2_2_class(pybind11::module &m);
#endif // AbstractCentreBasedCellPopulation2_2_hpp__cppwg_wrapper
