#ifndef AbstractSimplePhaseBasedCellCycleModel_hpp__cppwg_wrapper
#define AbstractSimplePhaseBasedCellCycleModel_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractSimplePhaseBasedCellCycleModel_class(pybind11::module &m);
#endif // AbstractSimplePhaseBasedCellCycleModel_hpp__cppwg_wrapper
