#ifndef AbstractCellPopulationCountWriter3_3_hpp__cppwg_wrapper
#define AbstractCellPopulationCountWriter3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractCellPopulationCountWriter3_3_class(pybind11::module &m);
#endif // AbstractCellPopulationCountWriter3_3_hpp__cppwg_wrapper
