#ifndef AbstractSimpleGenerationalCellCycleModel_hpp__cppwg_wrapper
#define AbstractSimpleGenerationalCellCycleModel_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractSimpleGenerationalCellCycleModel_class(pybind11::module &m);
#endif // AbstractSimpleGenerationalCellCycleModel_hpp__cppwg_wrapper
