#ifndef AbstractImmersedBoundaryDivisionRule3_hpp__cppwg_wrapper
#define AbstractImmersedBoundaryDivisionRule3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractImmersedBoundaryDivisionRule3_class(pybind11::module &m);
#endif // AbstractImmersedBoundaryDivisionRule3_hpp__cppwg_wrapper
