#ifndef AttractingPlaneBoundaryCondition3_3_hpp__cppwg_wrapper
#define AttractingPlaneBoundaryCondition3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AttractingPlaneBoundaryCondition3_3_class(pybind11::module &m);
#endif // AttractingPlaneBoundaryCondition3_3_hpp__cppwg_wrapper
