#ifndef AttractingPlaneBoundaryCondition2_2_hpp__cppwg_wrapper
#define AttractingPlaneBoundaryCondition2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AttractingPlaneBoundaryCondition2_2_class(pybind11::module &m);
#endif // AttractingPlaneBoundaryCondition2_2_hpp__cppwg_wrapper
