#ifndef CellsGeneratorGammaG1CellCycleModel_2_hpp__cppwg_wrapper
#define CellsGeneratorGammaG1CellCycleModel_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorGammaG1CellCycleModel_2_class(pybind11::module &m);
#endif // CellsGeneratorGammaG1CellCycleModel_2_hpp__cppwg_wrapper
