#ifndef CellsGeneratorAlarcon2004OxygenBasedCellCycleModel_3_hpp__cppwg_wrapper
#define CellsGeneratorAlarcon2004OxygenBasedCellCycleModel_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorAlarcon2004OxygenBasedCellCycleModel_3_class(pybind11::module &m);
#endif // CellsGeneratorAlarcon2004OxygenBasedCellCycleModel_3_hpp__cppwg_wrapper
