#ifndef CellsGeneratorContactInhibitionCellCycleModel_2_hpp__cppwg_wrapper
#define CellsGeneratorContactInhibitionCellCycleModel_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorContactInhibitionCellCycleModel_2_class(pybind11::module &m);
#endif // CellsGeneratorContactInhibitionCellCycleModel_2_hpp__cppwg_wrapper
