#ifndef CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_2_hpp__cppwg_wrapper
#define CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_2_class(pybind11::module &m);
#endif // CellsGeneratorLabelDependentBernoulliTrialCellCycleModel_2_hpp__cppwg_wrapper
