#ifndef CellsGeneratorFixedSequenceCellCycleModel_3_hpp__cppwg_wrapper
#define CellsGeneratorFixedSequenceCellCycleModel_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorFixedSequenceCellCycleModel_3_class(pybind11::module &m);
#endif // CellsGeneratorFixedSequenceCellCycleModel_3_hpp__cppwg_wrapper
