#ifndef CellsGeneratorUniformCellCycleModel_2_hpp__cppwg_wrapper
#define CellsGeneratorUniformCellCycleModel_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorUniformCellCycleModel_2_class(pybind11::module &m);
#endif // CellsGeneratorUniformCellCycleModel_2_hpp__cppwg_wrapper
