#ifndef CellsGeneratorTysonNovakCellCycleModel_2_hpp__cppwg_wrapper
#define CellsGeneratorTysonNovakCellCycleModel_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorTysonNovakCellCycleModel_2_class(pybind11::module &m);
#endif // CellsGeneratorTysonNovakCellCycleModel_2_hpp__cppwg_wrapper
