#ifndef CellsGeneratorUniformCellCycleModel_3_hpp__cppwg_wrapper
#define CellsGeneratorUniformCellCycleModel_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorUniformCellCycleModel_3_class(pybind11::module &m);
#endif // CellsGeneratorUniformCellCycleModel_3_hpp__cppwg_wrapper
