#ifndef CellsGeneratorExponentialG1GenerationalCellCycleModel_3_hpp__cppwg_wrapper
#define CellsGeneratorExponentialG1GenerationalCellCycleModel_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorExponentialG1GenerationalCellCycleModel_3_class(pybind11::module &m);
#endif // CellsGeneratorExponentialG1GenerationalCellCycleModel_3_hpp__cppwg_wrapper
