#ifndef CellPopulationAdjacencyMatrixWriter3_3_hpp__cppwg_wrapper
#define CellPopulationAdjacencyMatrixWriter3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellPopulationAdjacencyMatrixWriter3_3_class(pybind11::module &m);
#endif // CellPopulationAdjacencyMatrixWriter3_3_hpp__cppwg_wrapper
