#ifndef CellCycleModelProteinConcentrationsWriter2_2_hpp__cppwg_wrapper
#define CellCycleModelProteinConcentrationsWriter2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellCycleModelProteinConcentrationsWriter2_2_class(pybind11::module &m);
#endif // CellCycleModelProteinConcentrationsWriter2_2_hpp__cppwg_wrapper
