#ifndef CellProliferativeTypesCountWriter2_2_hpp__cppwg_wrapper
#define CellProliferativeTypesCountWriter2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellProliferativeTypesCountWriter2_2_class(pybind11::module &m);
#endif // CellProliferativeTypesCountWriter2_2_hpp__cppwg_wrapper
