#ifndef CellCycleModelProteinConcentrationsWriter3_3_hpp__cppwg_wrapper
#define CellCycleModelProteinConcentrationsWriter3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellCycleModelProteinConcentrationsWriter3_3_class(pybind11::module &m);
#endif // CellCycleModelProteinConcentrationsWriter3_3_hpp__cppwg_wrapper
