#ifndef CellsGeneratorBernoulliTrialCellCycleModel_2_hpp__cppwg_wrapper
#define CellsGeneratorBernoulliTrialCellCycleModel_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorBernoulliTrialCellCycleModel_2_class(pybind11::module &m);
#endif // CellsGeneratorBernoulliTrialCellCycleModel_2_hpp__cppwg_wrapper
