#ifndef CellProliferativePhasesCountWriter3_3_hpp__cppwg_wrapper
#define CellProliferativePhasesCountWriter3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellProliferativePhasesCountWriter3_3_class(pybind11::module &m);
#endif // CellProliferativePhasesCountWriter3_3_hpp__cppwg_wrapper
