#ifndef CellProliferativePhasesCountWriter2_2_hpp__cppwg_wrapper
#define CellProliferativePhasesCountWriter2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellProliferativePhasesCountWriter2_2_class(pybind11::module &m);
#endif // CellProliferativePhasesCountWriter2_2_hpp__cppwg_wrapper
