#ifndef CellsGeneratorStochasticOxygenBasedCellCycleModel_3_hpp__cppwg_wrapper
#define CellsGeneratorStochasticOxygenBasedCellCycleModel_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellsGeneratorStochasticOxygenBasedCellCycleModel_3_class(pybind11::module &m);
#endif // CellsGeneratorStochasticOxygenBasedCellCycleModel_3_hpp__cppwg_wrapper
