#ifndef DifferentialAdhesionPottsUpdateRule3_hpp__cppwg_wrapper
#define DifferentialAdhesionPottsUpdateRule3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_DifferentialAdhesionPottsUpdateRule3_class(pybind11::module &m);
#endif // DifferentialAdhesionPottsUpdateRule3_hpp__cppwg_wrapper
