#ifndef DifferentialAdhesionGeneralisedLinearSpringForce3_3_hpp__cppwg_wrapper
#define DifferentialAdhesionGeneralisedLinearSpringForce3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_DifferentialAdhesionGeneralisedLinearSpringForce3_3_class(pybind11::module &m);
#endif // DifferentialAdhesionGeneralisedLinearSpringForce3_3_hpp__cppwg_wrapper
