#ifndef DifferentialAdhesionGeneralisedLinearSpringForce2_2_hpp__cppwg_wrapper
#define DifferentialAdhesionGeneralisedLinearSpringForce2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_DifferentialAdhesionGeneralisedLinearSpringForce2_2_class(pybind11::module &m);
#endif // DifferentialAdhesionGeneralisedLinearSpringForce2_2_hpp__cppwg_wrapper
