#ifndef ImmersedBoundaryMorseMembraneForce3_hpp__cppwg_wrapper
#define ImmersedBoundaryMorseMembraneForce3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundaryMorseMembraneForce3_class(pybind11::module &m);
#endif // ImmersedBoundaryMorseMembraneForce3_hpp__cppwg_wrapper
