#ifndef ImmersedBoundaryLinearDifferentialAdhesionForce2_hpp__cppwg_wrapper
#define ImmersedBoundaryLinearDifferentialAdhesionForce2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundaryLinearDifferentialAdhesionForce2_class(pybind11::module &m);
#endif // ImmersedBoundaryLinearDifferentialAdhesionForce2_hpp__cppwg_wrapper
