#ifndef ImmersedBoundaryKinematicFeedbackForce2_hpp__cppwg_wrapper
#define ImmersedBoundaryKinematicFeedbackForce2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundaryKinematicFeedbackForce2_class(pybind11::module &m);
#endif // ImmersedBoundaryKinematicFeedbackForce2_hpp__cppwg_wrapper
