#ifndef ImmersedBoundaryNeighbourNumberWriter2_2_hpp__cppwg_wrapper
#define ImmersedBoundaryNeighbourNumberWriter2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundaryNeighbourNumberWriter2_2_class(pybind11::module &m);
#endif // ImmersedBoundaryNeighbourNumberWriter2_2_hpp__cppwg_wrapper
