#ifndef ImmersedBoundaryNeighbourNumberWriter3_3_hpp__cppwg_wrapper
#define ImmersedBoundaryNeighbourNumberWriter3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundaryNeighbourNumberWriter3_3_class(pybind11::module &m);
#endif // ImmersedBoundaryNeighbourNumberWriter3_3_hpp__cppwg_wrapper
