#ifndef ImmersedBoundarySimulationModifier2_hpp__cppwg_wrapper
#define ImmersedBoundarySimulationModifier2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundarySimulationModifier2_class(pybind11::module &m);
#endif // ImmersedBoundarySimulationModifier2_hpp__cppwg_wrapper
