#ifndef ImmersedBoundaryLinearInteractionForce3_hpp__cppwg_wrapper
#define ImmersedBoundaryLinearInteractionForce3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundaryLinearInteractionForce3_class(pybind11::module &m);
#endif // ImmersedBoundaryLinearInteractionForce3_hpp__cppwg_wrapper
