#ifndef ImmersedBoundaryLinearMembraneForce2_hpp__cppwg_wrapper
#define ImmersedBoundaryLinearMembraneForce2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundaryLinearMembraneForce2_class(pybind11::module &m);
#endif // ImmersedBoundaryLinearMembraneForce2_hpp__cppwg_wrapper
