#ifndef ImmersedBoundaryKinematicFeedbackForce3_hpp__cppwg_wrapper
#define ImmersedBoundaryKinematicFeedbackForce3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundaryKinematicFeedbackForce3_class(pybind11::module &m);
#endif // ImmersedBoundaryKinematicFeedbackForce3_hpp__cppwg_wrapper
