#ifndef ImmersedBoundaryLinearDifferentialAdhesionForce3_hpp__cppwg_wrapper
#define ImmersedBoundaryLinearDifferentialAdhesionForce3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ImmersedBoundaryLinearDifferentialAdhesionForce3_class(pybind11::module &m);
#endif // ImmersedBoundaryLinearDifferentialAdhesionForce3_hpp__cppwg_wrapper
