#ifndef LegacyCellProliferativeTypesWriter2_2_hpp__cppwg_wrapper
#define LegacyCellProliferativeTypesWriter2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_LegacyCellProliferativeTypesWriter2_2_class(pybind11::module &m);
#endif // LegacyCellProliferativeTypesWriter2_2_hpp__cppwg_wrapper
