#ifndef LegacyCellProliferativeTypesWriter3_3_hpp__cppwg_wrapper
#define LegacyCellProliferativeTypesWriter3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_LegacyCellProliferativeTypesWriter3_3_class(pybind11::module &m);
#endif // LegacyCellProliferativeTypesWriter3_3_hpp__cppwg_wrapper
