#ifndef MeshBasedCellPopulationWithGhostNodes3_hpp__cppwg_wrapper
#define MeshBasedCellPopulationWithGhostNodes3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_MeshBasedCellPopulationWithGhostNodes3_class(pybind11::module &m);
#endif // MeshBasedCellPopulationWithGhostNodes3_hpp__cppwg_wrapper
