#ifndef MeshBasedCellPopulationWithGhostNodes2_hpp__cppwg_wrapper
#define MeshBasedCellPopulationWithGhostNodes2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_MeshBasedCellPopulationWithGhostNodes2_class(pybind11::module &m);
#endif // MeshBasedCellPopulationWithGhostNodes2_hpp__cppwg_wrapper
