#ifndef NagaiHondaDifferentialAdhesionForce3_hpp__cppwg_wrapper
#define NagaiHondaDifferentialAdhesionForce3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_NagaiHondaDifferentialAdhesionForce3_class(pybind11::module &m);
#endif // NagaiHondaDifferentialAdhesionForce3_hpp__cppwg_wrapper
