#ifndef NagaiHondaDifferentialAdhesionForce2_hpp__cppwg_wrapper
#define NagaiHondaDifferentialAdhesionForce2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_NagaiHondaDifferentialAdhesionForce2_class(pybind11::module &m);
#endif // NagaiHondaDifferentialAdhesionForce2_hpp__cppwg_wrapper
