#ifndef NodeBasedCellPopulationWithBuskeUpdate3_hpp__cppwg_wrapper
#define NodeBasedCellPopulationWithBuskeUpdate3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_NodeBasedCellPopulationWithBuskeUpdate3_class(pybind11::module &m);
#endif // NodeBasedCellPopulationWithBuskeUpdate3_hpp__cppwg_wrapper
