#ifndef NodeBasedCellPopulationWithBuskeUpdate2_hpp__cppwg_wrapper
#define NodeBasedCellPopulationWithBuskeUpdate2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_NodeBasedCellPopulationWithBuskeUpdate2_class(pybind11::module &m);
#endif // NodeBasedCellPopulationWithBuskeUpdate2_hpp__cppwg_wrapper
