#ifndef NodeBasedCellPopulationWithParticles3_hpp__cppwg_wrapper
#define NodeBasedCellPopulationWithParticles3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_NodeBasedCellPopulationWithParticles3_class(pybind11::module &m);
#endif // NodeBasedCellPopulationWithParticles3_hpp__cppwg_wrapper
