#ifndef NodeBasedCellPopulationWithParticles2_hpp__cppwg_wrapper
#define NodeBasedCellPopulationWithParticles2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_NodeBasedCellPopulationWithParticles2_class(pybind11::module &m);
#endif // NodeBasedCellPopulationWithParticles2_hpp__cppwg_wrapper
