#ifndef NormallyDistributedTargetAreaModifier2_hpp__cppwg_wrapper
#define NormallyDistributedTargetAreaModifier2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_NormallyDistributedTargetAreaModifier2_class(pybind11::module &m);
#endif // NormallyDistributedTargetAreaModifier2_hpp__cppwg_wrapper
