#ifndef NormallyDistributedTargetAreaModifier3_hpp__cppwg_wrapper
#define NormallyDistributedTargetAreaModifier3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_NormallyDistributedTargetAreaModifier3_class(pybind11::module &m);
#endif // NormallyDistributedTargetAreaModifier3_hpp__cppwg_wrapper
