#ifndef RandomDirectionVertexBasedDivisionRule3_hpp__cppwg_wrapper
#define RandomDirectionVertexBasedDivisionRule3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_RandomDirectionVertexBasedDivisionRule3_class(pybind11::module &m);
#endif // RandomDirectionVertexBasedDivisionRule3_hpp__cppwg_wrapper
