#ifndef RandomDirectionVertexBasedDivisionRule2_hpp__cppwg_wrapper
#define RandomDirectionVertexBasedDivisionRule2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_RandomDirectionVertexBasedDivisionRule2_class(pybind11::module &m);
#endif // RandomDirectionVertexBasedDivisionRule2_hpp__cppwg_wrapper
