#ifndef SurfaceAreaConstraintPottsUpdateRule2_hpp__cppwg_wrapper
#define SurfaceAreaConstraintPottsUpdateRule2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_SurfaceAreaConstraintPottsUpdateRule2_class(pybind11::module &m);
#endif // SurfaceAreaConstraintPottsUpdateRule2_hpp__cppwg_wrapper
