#!/usr/bin/env python

"""
Figure out the best version number for the chaste-source package, and
write the debian/changelog file appropriately.

The script expects to be run in a checked-out and fully up-to-date Chaste
root folder, and will use subversion to determine the version.  If the
working copy is checked out from a tag, then the corresponding release
number (formatted as n.m) will be used.  If it's from trunk, then we are
making a point release, including the current svn version as a third
component (e.g. n.m.rrrr).  We look for the latest release that is earlier
than the checked-out revision to determine "n.m".
"""

import os
import sys
import time

# Configuration
maintainer_email = 'chaste-admin@maillist.ox.ac.uk'
package_name = 'chaste-source'
ubuntu_version = 'precise'


# Check that the cwd looks OK
changelog = 'debian/changelog'
if not os.path.exists(changelog):
    print >>sys.stderr, changelog, "file not found; are you in a Chaste working copy?"
    sys.exit(1)

# Get the current commit details
num_commits = int(os.popen('git rev-list HEAD | wc -l').read().strip())
commit_sha = os.popen('git rev-parse HEAD').read().strip()

# Find out where we're checked out from
tag = os.popen('git tag --points-at HEAD').readline().strip()
branch = ''
if not tag:
    pipe = os.popen('git branch --contains HEAD')
    for line in pipe:
        if line.startswith('*'):
            branch = line[1:].strip()
            break
    pipe.close()

print "Packaging tag", tag, "branch", branch

def release_version(version):
    """Ensure we have a version in the form n.m (not just n)."""
    parts = version.split('.')
    if len(parts) < 1:
        raise ValueError('Empty version string')
    elif len(parts) < 2:
        version = version + '.0'
    elif len(parts) > 2:
        raise ValueError('Too many version components')
    return version

def version_as_int(version):
    """Convert a version string n.m to an integer n*1000+m."""
    n, m = version.split('.')
    return int(n)*1000 + int(m)

# And now work out the version
if tag:
    assert tag.startswith('release_')
    package_version = release_version(tag[8:])
    message = 'Package release %s of Chaste.' % package_version
else:
    # Now we've got to be clever.  Look for the most recent release in tags.
    latest_release = '0.0'
    pipe = os.popen('git tag -l')
    for line in pipe:
        tag = line.strip()
        if tag.startswith('release_'):
            version = release_version(tag[8:])
            if version_as_int(version) > version_as_int(latest_release):
                latest_release = version
    pipe.close()
    package_version = '%s.9%d.r%s' % (latest_release, num_commits, commit_sha)
    message = 'Package commit %s in Chaste %s.' % (commit_sha, latest_release)
    # Write version number for benefit of SCons
    open('ReleaseVersion.txt', 'w').write(package_version)

print "Version is", package_version

# Check if we're likely to package any projects
projects = filter(lambda s: s[0] != '.',
                  os.listdir('projects'))
if projects:
    print "Projects exist.  Do you really want to include them?"
    print projects

subst = {'package': package_name,
         'version': package_version,
         'distro': ubuntu_version,
         'addr': maintainer_email,
         'message': message,
         'date': time.strftime("%a, %d %b %Y %H:%M:%S +0000", time.gmtime())}

log_entry = """%(package)s (%(version)s) %(distro)s; urgency=low

  * %(message)s

 -- Chaste Team <%(addr)s>  %(date)s

""" % subst

# Write changelog and launch editor
current_changelog = open(changelog).read()
os.rename(changelog, changelog + '.bak')
fp = open(changelog, 'w')
fp.write(log_entry)
fp.write(current_changelog)
fp.close()
print "Please open", changelog, "in your editor to check the contents."
