#ifndef CellPopulationPyChasteActorGenerator2_hpp__cppwg_wrapper
#define CellPopulationPyChasteActorGenerator2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_CellPopulationPyChasteActorGenerator2_class(pybind11::module &m);
#endif // CellPopulationPyChasteActorGenerator2_hpp__cppwg_wrapper
