option(ENABLE_global_TESTING "Generate the test infrastructure for the global component" ON)
mark_as_advanced(ENABLE_global_TESTING)
option(ENABLE_io_TESTING "Generate the test infrastructure for the io component" ON)
mark_as_advanced(ENABLE_io_TESTING)
option(ENABLE_linalg_TESTING "Generate the test infrastructure for the linalg component" ON)
mark_as_advanced(ENABLE_linalg_TESTING)
option(ENABLE_mesh_TESTING "Generate the test infrastructure for the mesh component" ON)
mark_as_advanced(ENABLE_mesh_TESTING)
option(ENABLE_ode_TESTING "Generate the test infrastructure for the ode component" ON)
mark_as_advanced(ENABLE_ode_TESTING)
option(ENABLE_pde_TESTING "Generate the test infrastructure for the pde component" ON)
mark_as_advanced(ENABLE_pde_TESTING)
option(ENABLE_cell_based_TESTING "Generate the test infrastructure for the cell_based component" ON)
mark_as_advanced(ENABLE_cell_based_TESTING)
option(ENABLE_crypt_TESTING "Generate the test infrastructure for the crypt component" ON)
mark_as_advanced(ENABLE_crypt_TESTING)
option(ENABLE_continuum_mechanics_TESTING "Generate the test infrastructure for the continuum_mechanics component" ON)
mark_as_advanced(ENABLE_continuum_mechanics_TESTING)
option(ENABLE_heart_TESTING "Generate the test infrastructure for the heart component" ON)
mark_as_advanced(ENABLE_heart_TESTING)
option(ENABLE_continuum_mechanics_TESTING "Generate the test infrastructure for the continuum_mechanics component" ON)
mark_as_advanced(ENABLE_continuum_mechanics_TESTING)
