name: Coverage

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - develop

jobs:
  
  build-and-test:

    runs-on: ubuntu-22.04

    env:
      CHASTE_TEST_OUTPUT: ${{ github.workspace }}/chaste-test-dir
      CC: gcc
      CXX: g++

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: install dependencies
      run: |
        echo 'deb [signed-by=/usr/share/keyrings/chaste.asc] https://www.cs.ox.ac.uk/chaste/ubuntu focal/' | sudo tee -a /etc/apt/sources.list.d/chaste.list
        sudo wget -O /usr/share/keyrings/chaste.asc https://www.cs.ox.ac.uk/chaste/ubuntu/ChasteTeam.asc
        sudo apt update
        sudo apt install chaste-dependencies
        sudo apt install lcov

    - name: compiler version
      run: |
        ${CXX} --version

    - name: make build and test directories
      run: |
        mkdir -p chaste-build-dir
        mkdir -p ${CHASTE_TEST_OUTPUT}

    - name: cmake configure
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DChaste_COVERAGE_CPUS=2 ..
      working-directory: chaste-build-dir

    - name: build test suites
      run: cmake --build . --target Continuous Parallel --parallel 2
      working-directory: chaste-build-dir

    - name: run test suites
      run: |
        ctest -j2 -L Continuous --output-on-failure
        ctest -L Parallel  --output-on-failure
      working-directory: chaste-build-dir

    - name: run coverage
      run: |
        lcov --config-file ../cmake/Config/lcovrc --directory . --capture --output-file coverage.info
        lcov --config-file ../cmake/Config/lcovrc --remove coverage.info '/usr/*' '*/fortests/*' '*/test/*' '*/3rdparty/*' '*/global/src/random/*' 'Debug/*' 'Debug_*/*' '*/cxxtest/*' --output-file coverage.info
      working-directory: chaste-build-dir

    - name: upload to codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov
      working-directory: chaste-build-dir
