name: Build chaste/develop

on:
  push:
    branches: [ "develop" ]
  # Schedule a weekly build on Sunday at 1am after rebuilding the base image
  schedule:
    - cron: '0 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # https://github.com/actions/checkout/
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      # https://github.com/docker/metadata-action
      with:
        images: |
          chaste/develop
        flavor: latest=true
        tags: |
          type=schedule,pattern={{date 'YYYYMMDD'}}
          type=ref,event=pr
          type=sha
        labels: |
          org.opencontainers.image.title=Chaste Develop Image
          org.opencontainers.image.description=Docker Develop Image for Chaste: Cancer, Heart and Soft Tissue Environment
          org.opencontainers.image.url=https://hub.docker.com/repository/docker/chaste/develop/general
          org.opencontainers.image.source=https://github.com/Chaste/chaste-docker
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-qemu-action
      with:
        platforms: 'amd64,arm64'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      # https://github.com/docker/setup-buildx-action
    - name: Login to DockerHub
      uses: docker/login-action@v3
      # https://github.com/docker/login-action
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v5
      # https://github.com/docker/build-push-action
      with:
        context: .
        file: docker/Dockerfile
        build-args: |
            'GIT_TAG=.'
            'CMAKE_BUILD_TYPE="Debug"'
            'Chaste_ERROR_ON_WARNING="ON"'
            'Chaste_UPDATE_PROVENANCE="OFF"'
        platforms: 'amd64,arm64'
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
