name: Build chaste/release

on:
  release:
    types: [ published ]
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # Schedule a weekly build on Sunday at 3am after rebuilding the base image
  schedule:
    - cron: '0 3 * * 0'

jobs:
  build:
    runs-on: self-hosted-docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # https://github.com/actions/checkout/
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      # https://github.com/docker/metadata-action
      with:
        images: |
          chaste/release
        flavor: latest=true
        tags: |
          type=schedule,pattern={{date 'YYYYMMDD'}}
          # type=semver,pattern={{raw}}
          type=semver,pattern={{version}}
          # type=match,pattern=release_(\d.\d)
          type=ref,event=tag
        labels: |
          org.opencontainers.image.title=Chaste Release Image
          org.opencontainers.image.description=Docker Release Image for Chaste: Cancer, Heart and Soft Tissue Environment
          org.opencontainers.image.url=https://hub.docker.com/repository/docker/chaste/releases
          org.opencontainers.image.source=https://github.com/Chaste/chaste-docker
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-qemu-action
      with:
        platforms: 'amd64,arm64'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      # https://github.com/docker/setup-buildx-action
    - name: Login to DockerHub
      uses: docker/login-action@v3
      # https://github.com/docker/login-action
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v5
      # https://github.com/docker/build-push-action
      with:
        context: .
        file: docker/Dockerfile
        build-args: |
            'GIT_TAG=.'
            'CMAKE_BUILD_TYPE="Release"'
            'Chaste_ERROR_ON_WARNING="OFF"'
            'Chaste_UPDATE_PROVENANCE="ON"'
        platforms: 'amd64,arm64'
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
