name: pychaste-tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

# Limit concurrent runs to one per branch
concurrency:
  group: pychaste-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pychaste-tests:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:off') }}

    runs-on: ubuntu-22.04
    env:
      CHASTE_TEST_OUTPUT: ${{ github.workspace }}/chaste_test_output

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make build and test directories
        run: |
          mkdir -p build
          mkdir -p ${CHASTE_TEST_OUTPUT}

      - name: Install Chaste dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake \
            cmake-curses-gui \
            doxygen \
            g++ \
            git \
            gnuplot \
            graphviz \
            hdf5-tools \
            lcov \
            libboost-serialization-dev \
            libboost-filesystem-dev \
            libboost-program-options-dev \
            libfltk1.1 \
            libhdf5-openmpi-dev \
            libmetis-dev \
            libopenmpi-dev \
            libparmetis-dev \
            libpetsc-real3.15-dbg \
            libsundials-dev \
            libvtk7-dev \
            libxerces-c-dev \
            mencoder \
            paraview \
            petsc-dev \
            python3 \
            python3-dev \
            python3-pip \
            python3-venv \
            valgrind \
            xsdcxx

      - name: Install PyChaste-specific dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-matplotlib \
            python3-notebook \
            python3-numpy \
            python3-petsc4py \
            python3-vtk7 \
            python3-xvfbwrapper \
            xvfb
          sudo python3 -m pip install --upgrade pip

      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DChaste_ENABLE_PYCHASTE=ON ..
        working-directory: build

      - name: Re-generate PyChaste wrappers
        run: |
          mv pychaste/dynamic/wrappers pychaste/dynamic/wrappers.bak
          cd build
          make pychaste_wrappers
          cd ..
          mv pychaste/dynamic/wrappers pychaste/dynamic/wrappers.gen
          mv pychaste/dynamic/wrappers.bak pychaste/dynamic/wrappers

      - name: Find unknown classes
        run: |
          CPPWG_LOG="$(pwd)/build/pychaste/cppwg.log"
          test -f $CPPWG_LOG || exit 1

          CELL_BASED_SRC="$(pwd)/cell_based/src"
          test -d $CELL_BASED_SRC || exit 2

          CELL_BASED_FORTESTS="$CELL_BASED_SRC/fortests"
          test -d $CELL_BASED_FORTESTS || exit 3

          ! grep "Unknown class" "$CPPWG_LOG" |\
            grep "$CELL_BASED_SRC" |\
            grep -v "$CELL_BASED_FORTESTS" |\
            grep -v -e "Unknown class guid_defined<.*>\B" |\
            grep -v -e "Unknown class .*Iterator\b" \
          || exit 4

      - name: Compare existing and generated wrappers
        run: |
          ctest -V -R TestPyWrapperChanges$
        working-directory: build

      - name: Build
        run: |
          make -j $(nproc) pychaste
        working-directory: build

      - name: Install PyChaste
        run: |
          pip install --user build/pychaste/package

      - name: Run tests
        run: |
          xvfb-run --server-args="-screen 0 1024x768x24" \
            ctest -j $(nproc) -L pychaste --output-on-failure
        working-directory: build
