name: Ubuntu continuous test suite

on:
  push:
    branches:
      - release

jobs:
  
  build-and-test:
    name: Test on Ubuntu 18.04
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodule
      run: git submodule update --init
    - name: install dependencies
      run: |
        echo 'deb http://www.cs.ox.ac.uk/chaste/ubuntu bionic/' | sudo tee -a /etc/apt/sources.list.d/chaste.list
        sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 422C4D99
        sudo apt update
        sudo apt install chaste-dependencies
    - name: make build directory
      run: mkdir chaste-build-dir
    - name: cmake configure
      run: cmake ..
      working-directory: chaste-build-dir
    - name: cmake build
      run: cmake --build . --parallel 2 --target Continuous
      working-directory: chaste-build-dir
    - name: cmake test
      run: ctest -j2 -L Continuous --output-on-failure
      working-directory: chaste-build-dir
