name: Update tutorials

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  
  generate-tutorial-markdown:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:off') }}
    steps:
      - name: checkout Chaste
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history in order to get revision info for tutorial files

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: generate user-tutorial markdown
        run: |
          python GenerateUserTutorials.py
        working-directory: python/infra

      - name: Upload archive files
        uses: actions/upload-artifact@v3
        with:
          name: user-tutorial-markdown
          path: |
            tutorials/UserTutorials/*.md

  upload-to-website:
    needs: generate-tutorial-markdown
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Download user-tutorial-to markdown
        uses: actions/download-artifact@v3
        with:
          name: user-tutorial-markdown
          path: tutorials/UserTutorials

      - name: Checkout website repository
        uses: actions/checkout@v4
        with:
          repository: Chaste/Chaste.github.io
          token: ${{ secrets.WEBSITE_ACCESS }}
          path: chaste-website
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Display structure of downloaded files
        run: ls -R

      - name: Copy markdown to website repository
        run: |
          cp tutorials/UserTutorials/*.md chaste-website/site/content/docs/user-tutorials/

      - name: Commit and push if changed
        run: |
          git config user.name "github-action"
          git config user.email "github-action"
          git add --all
          git commit -m "update user tutorials" || echo "No changes to commit"
          git push
        working-directory: chaste-website
